# Generated by Django 2.2.6 on 2019-10-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0002_auto_20191010_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
